unit FreeStringsUnit;

interface

Type TUserstring   = record
                        ID     : Integer;
                        Value  : string;
                     end;

const UserStrings:array[0..295] of TUserstring =(
   (ID:0275; Value:'according to John Winters'),
   (ID:0131; Value:'Add cylinder'),
   (ID:0130; Value:'Add flowline'),
   (ID:0227; Value:'Add multiple buttocks'),
   (ID:0233; Value:'Add multiple diagonals'),
   (ID:0224; Value:'Add multiple stations'),
   (ID:0230; Value:'Add multiple waterlines'),
   (ID:0226; Value:'Add one buttock'),
   (ID:0232; Value:'Add one diagonal'),
   (ID:0223; Value:'Add one station'),
   (ID:0229; Value:'Add one waterline'),
   (ID:0171; Value:'align points'),
   (ID:0172; Value:'All of the selected points are locked and cannot be moved'),
   (ID:0148; Value:'analyze surface'),
   (ID:0206; Value:'and'),
   (ID:0188; Value:'and cannot be opened with this version'),
   (ID:0051; Value:'Appendage coefficient'),
   (ID:0087; Value:'Are you sure you want to continue?'),
   (ID:0143; Value:'Are you sure you want to delete all the markers?'),
   (ID:0173; Value:'Are you sure you want to delete the'),
   (ID:0068; Value:'Are you sure you want to delete this background image?'),
   (ID:0282; Value:'Are you sure you want to quit'),
   (ID:0247; Value:'Are you sure you want to reset the preferences'),
   (ID:0034; Value:'Area'),
   (ID:0166; Value:'At least two layers are needed to perform this operation.'),
   (ID:0260; Value:'Average chordlength'),
   (ID:0219; Value:'Background image settings'),
   (ID:0184; Value:'Base'),
   (ID:0018; Value:'Beam on waterline'),
   (ID:0047; Value:'Beam over all'),
   (ID:0007; Value:'Block coefficient'),
   (ID:0215; Value:'Bodyplan view'),
   (ID:0059; Value:'Buttock'),
   (ID:0063; Value:'Buttocks'),
   (ID:0268; Value:'Bwl/Tc is outside valid domain'),
   (ID:0263; Value:'Calculated variables'),
   (ID:0294; Value:'Calculation aborted'),
   (ID:0245; Value:'Center'),
   (ID:0183; Value:'Centerline'),
   (ID:0209; Value:'Choose a directory where you want to save the dxf files to:'),
   (ID:0187; Value:'Close hull'),
   (ID:0160; Value:'collapse point'),
   (ID:0042; Value:'Comment'),
   (ID:0080; Value:'controlface(s) could be removed.'),
   (ID:0081; Value:'controlpoints(s) could be removed.'),
   (ID:0213; Value:'corner'),
   (ID:0199; Value:'Could not calculate limitpoint'),
   (ID:0100; Value:'Could not export surfaces.'),
   (ID:0201; Value:'Could not find edge'),
   (ID:0099; Value:'Could not find the interior point!'),
   (ID:0176; Value:'Could not load program preferences from the following location'),
   (ID:0133; Value:'Could not open the file.'),
   (ID:0177; Value:'Could not save program preferences to the following location'),
   (ID:0271; Value:'Cp is outside valid domain'),
   (ID:0041; Value:'Created by'),
   (ID:0293; Value:'Cross curves'),
   (ID:0289; Value:'curves'),
   (ID:0181; Value:'Date'),
   (ID:0175; Value:'delete'),
   (ID:0228; Value:'Delete all buttocks'),
   (ID:0234; Value:'Delete all diagonals'),
   (ID:0225; Value:'Delete all stations'),
   (ID:0231; Value:'Delete all waterlines'),
   (ID:0140; Value:'delete empty layers'),
   (ID:0144; Value:'delete markers'),
   (ID:0046; Value:'Design beam'),
   (ID:0048; Value:'Design draft'),
   (ID:0044; Value:'Design length'),
   (ID:0040; Value:'Designer'),
   (ID:0061; Value:'Diagonal'),
   (ID:0065; Value:'Diagonals'),
   (ID:0003; Value:'Displaced volume'),
   (ID:0004; Value:'Displacement'),
   (ID:0292; Value:'Displacement step can not be zero.'),
   (ID:0236; Value:'Distance'),
   (ID:0180; Value:'Do you want to adjust the markers too'),
   (ID:0111; Value:'Do you want to import the intermediate bulkheads?'),
   (ID:0070; Value:'Do you want to replace it with another one?'),
   (ID:0104; Value:'Do you want to save it first?'),
   (ID:0127; Value:'Do you want to save the file as version'),
   (ID:0158; Value:'double edges'),
   (ID:0257; Value:'Draft hull'),
   (ID:0185; Value:'DWL'),
   (ID:0202; Value:'Edge already exists'),
   (ID:0073; Value:'edge collapse'),
   (ID:0076; Value:'edge extrusion'),
   (ID:0078; Value:'edge split'),
   (ID:0287; Value:'edges'),
   (ID:0155; Value:'edges found with more then 2 faces connected to it!'),
   (ID:0276; Value:'Effective waterline length'),
   (ID:0141; Value:'empty layers deleted'),
   (ID:0253; Value:'End speed'),
   (ID:0194; Value:'Enter the printscale'),
   (ID:0022; Value:'Entrance angle'),
   (ID:0132; Value:'Error in line'),
   (ID:0192; Value:'Error reading from file'),
   (ID:0098; Value:'Error while assembling triangle!'),
   (ID:0266; Value:'Estimated'),
   (ID:0286; Value:'faces'),
   (ID:0043; Value:'Filename'),
   (ID:0264; Value:'Final calculations of resistance'),
   (ID:0083; Value:'flip normals'),
   (ID:0246; Value:'FREE!ship linesplan'),
   (ID:0214; Value:'FREE!ship plate developments'),
   (ID:0251; Value:'General'),
   (ID:0277; Value:'Half entrance-angle of dwl'),
   (ID:0256; Value:'Hull'),
   (ID:0109; Value:'import .Fef file'),
   (ID:0110; Value:'import .hul file'),
   (ID:0134; Value:'import bodyplan'),
   (ID:0105; Value:'import carene file'),
   (ID:0107; Value:'import chines'),
   (ID:0146; Value:'import markers'),
   (ID:0112; Value:'Import part'),
   (ID:0118; Value:'import PolyCad file'),
   (ID:0136; Value:'import surface'),
   (ID:0125; Value:'import VRML file'),
   (ID:0153; Value:'inconsistent normals'),
   (ID:0284; Value:'Incr. distance'),
   (ID:0025; Value:'Initial stability'),
   (ID:0250; Value:'Input variables'),
   (ID:0163; Value:'insert plane intersections'),
   (ID:0122; Value:'Invalid contour distance.'),
   (ID:0197; Value:'Invalid coordinate'),
   (ID:0243; Value:'Invalid displacement'),
   (ID:0117; Value:'Invalid floating point value in surface'),
   (ID:0116; Value:'Invalid integer value in surface'),
   (ID:0108; Value:'Invalid unit identifier!'),
   (ID:0222; Value:'Invalid value'),
   (ID:0102; Value:'Invalid wave pattern file!'),
   (ID:0119; Value:'Invalid x-coordinate in surface'),
   (ID:0120; Value:'Invalid y-coordinate in surface'),
   (ID:0121; Value:'Invalid z-coordinate in surface'),
   (ID:0207; Value:'is no valid numeric input'),
   (ID:0241; Value:'iterations'),
   (ID:0274; Value:'KAPER resistance for canoes and kayaks'),
   (ID:0259; Value:'Keel'),
   (ID:0159; Value:'Lackenby tranformation'),
   (ID:0071; Value:'Last state'),
   (ID:0029; Value:'Lateral area'),
   (ID:0028; Value:'Lateral plane'),
   (ID:0033; Value:'Layer'),
   (ID:0139; Value:'layer grouping'),
   (ID:0164; Value:'layer intersection'),
   (ID:0244; Value:'layer properties'),
   (ID:0270; Value:'LCB is outside valid domain'),
   (ID:0150; Value:'leak points'),
   (ID:0017; Value:'Length on waterline'),
   (ID:0045; Value:'Length over all'),
   (ID:0057; Value:'Location'),
   (ID:0167; Value:'lock points'),
   (ID:0191; Value:'Locked points can not be moved!'),
   (ID:0011; Value:'Longitudinal center of buoyancy'),
   (ID:0030; Value:'Longitudinal center of effort'),
   (ID:0027; Value:'Longitudinal metacentric height'),
   (ID:0024; Value:'Longitudinal moment of inertia'),
   (ID:0267; Value:'Lwl/Bwl is outside valid domain'),
   (ID:0269; Value:'Lwl/Displ^3 is outside valid domain'),
   (ID:0067; Value:'Marker has no owner!'),
   (ID:0055; Value:'measured from the aft perpendicular at X=0.0'),
   (ID:0056; Value:'measured from the lowest point of the hull'),
   (ID:0101; Value:'Michlet export'),
   (ID:0015; Value:'Midship coefficient'),
   (ID:0049; Value:'Midship location'),
   (ID:0013; Value:'Midship properties'),
   (ID:0014; Value:'Midship section area'),
   (ID:0084; Value:'mirror'),
   (ID:0156; Value:'Model is ok.'),
   (ID:0280; Value:'modified'),
   (ID:0093; Value:'move'),
   (ID:0072; Value:'new controlcurve'),
   (ID:0196; Value:'New coordinate'),
   (ID:0074; Value:'new edge'),
   (ID:0094; Value:'new face'),
   (ID:0285; Value:'New increment distance'),
   (ID:0235; Value:'New intersection'),
   (ID:0142; Value:'new layer'),
   (ID:0157; Value:'new model'),
   (ID:0179; Value:'New model'),
   (ID:0237; Value:'New range of intersections'),
   (ID:0082; Value:'No faces could be removed.'),
   (ID:0123; Value:'No geometry imported.'),
   (ID:0165; Value:'No intersection points found.'),
   (ID:0147; Value:'No markers could be imported.'),
   (ID:0203; Value:'No meshdata could be imported'),
   (ID:0238; Value:'No points to transfom in the current selection'),
   (ID:0195; Value:'No printer assigned'),
   (ID:0154; Value:'normals flipped to point outward'),
   (ID:0200; Value:'Not all points could be added while collapsing edge'),
   (ID:0281; Value:'not modified'),
   (ID:0052; Value:'NOTE 1: Draft (and all other vertical heights) is measured above the lowest point of the hull!'),
   (ID:0053; Value:'NOTE 2: All calculated coefficients based on actual dimensions of submerged body.'),
   (ID:0054; Value:'NOTE 2: All calculated coefficients based on project length), draft and beam.'),
   (ID:0137; Value:'Number of columns'),
   (ID:0135; Value:'Number of desired controlpoints on each station'),
   (ID:0138; Value:'Number of rows'),
   (ID:0128; Value:'Old backup could not be removed!'),
   (ID:0077; Value:'Only boundary edges can be extruded!'),
   (ID:0151; Value:'Only the first 10 are shown'),
   (ID:0198; Value:'Part'),
   (ID:0218; Value:'Perspective view'),
   (ID:0217; Value:'Plan view'),
   (ID:0190; Value:'point move'),
   (ID:0288; Value:'points'),
   (ID:0162; Value:'points removed.'),
   (ID:0170; Value:'points unlocked'),
   (ID:0193; Value:'Print scale'),
   (ID:0008; Value:'Prismatic coefficient'),
   (ID:0216; Value:'Profile view'),
   (ID:0039; Value:'Project'),
   (ID:0178; Value:'project settings'),
   (ID:0291; Value:'Redo'),
   (ID:0079; Value:'remove starboard side'),
   (ID:0161; Value:'remove unused points'),
   (ID:0272; Value:'Resistance'),
   (ID:0265; Value:'Resistance according to Delft Systematic Yacht Series'),
   (ID:0089; Value:'rotate'),
   (ID:0088; Value:'Rotation vector'),
   (ID:0262; Value:'Rudder'),
   (ID:0091; Value:'scale'),
   (ID:0090; Value:'Scale vector'),
   (ID:0038; Value:'Sectional areas'),
   (ID:0174; Value:'selected items'),
   (ID:0075; Value:'set crease edges'),
   (ID:0221; Value:'Set tolerance'),
   (ID:0273; Value:'Speed'),
   (ID:0254; Value:'Speed step'),
   (ID:0252; Value:'Start speed'),
   (ID:0058; Value:'Station'),
   (ID:0062; Value:'Stations'),
   (ID:0186; Value:'Strake'),
   (ID:0278; Value:'Submerged transom area ratio'),
   (ID:0126; Value:'The current fileversion is version'),
   (ID:0103; Value:'The current model has been changed!'),
   (ID:0248; Value:'The current settings will be lost'),
   (ID:0124; Value:'The file contains no BSpline surfaces'),
   (ID:0152; Value:'The following items were corrected'),
   (ID:0032; Value:'The following layer properties are calculated for both sides of the ship'),
   (ID:0145; Value:'The model already contains markers. Do you want to delete those?'),
   (ID:0149; Value:'The model contains a total of'),
   (ID:0086; Value:'The selection contains locked points that will not be affected by this operation'),
   (ID:0001; Value:'The ship is making water at'),
   (ID:0069; Value:'There is already one backgroundimage assigned to this view.'),
   (ID:0001; Value:'There is no submersion'),
   (ID:0035; Value:'Thickness'),
   (ID:0113; Value:'This file was created with a later version of FREE!ship!'),
   (ID:0189; Value:'This is not a valid FREE!ship file!'),
   (ID:0114; Value:'This is not a valid FREE!ship part file!'),
   (ID:0208; Value:'This is not a valid VRML 1.0 file'),
   (ID:0239; Value:'This model contains locked points that will be modified by this operation'),
   (ID:0182; Value:'Time'),
   (ID:0037; Value:'Total'),
   (ID:0006; Value:'Total beam of submerged body'),
   (ID:0258; Value:'Total draft'),
   (ID:0005; Value:'Total length of submerged body'),
   (ID:0240; Value:'Transformation succeeded after'),
   (ID:0092; Value:'Translation vector'),
   (ID:0242; Value:'Transormation failed'),
   (ID:0220; Value:'Transparency tolerance'),
   (ID:0026; Value:'Transverse metacentric height'),
   (ID:0023; Value:'Transverse moment of inertia'),
   (ID:0129; Value:'Unable to create a backup file!'),
   (ID:0097; Value:'Unable to create file!'),
   (ID:0106; Value:'Unable to open file!'),
   (ID:0290; Value:'Undo'),
   (ID:0283; Value:'Undo memory'),
   (ID:0115; Value:'Unexpected end of file!'),
   (ID:0204; Value:'Unknown fileversion'),
   (ID:0066; Value:'Unknown intersection type'),
   (ID:0085; Value:'Unknown point in mirror command!'),
   (ID:0169; Value:'unlock all points'),
   (ID:0168; Value:'unlock points'),
   (ID:0205; Value:'Value must be between'),
   (ID:0279; Value:'Version'),
   (ID:0009; Value:'Vert. prismatic coefficient'),
   (ID:0012; Value:'Vertical center of buoyancy'),
   (ID:0031; Value:'Vertical center of effort'),
   (ID:0002; Value:'Volume properties'),
   (ID:0050; Value:'Water density'),
   (ID:0255; Value:'Water viscosity'),
   (ID:0060; Value:'Waterline'),
   (ID:0064; Value:'Waterlines'),
   (ID:0019; Value:'Waterplane area'),
   (ID:0021; Value:'Waterplane center of floatation'),
   (ID:0020; Value:'Waterplane coefficient'),
   (ID:0016; Value:'Waterplane properties'),
   (ID:0036; Value:'Weight'),
   (ID:0261; Value:'Wetted area'),
   (ID:0010; Value:'Wetted surface area'),
   (ID:0210; Value:'X coordinate'),
   (ID:0211; Value:'Y coordinate'),
   (ID:0249; Value:'YachtRes, resistance prediction for sailing yachts, according to Prof. Gerritsma'),
   (ID:0096; Value:'You have to set the mainparticulars first!'),
   (ID:0095; Value:'You need to select at least 3 controlpoints to create a new controlface'),
   (ID:0295; Value:'Heeling angle'),
   (ID:0212; Value:'Z coordinate')
);

implementation

end.
